// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/omniva-variants/CardPage.tsx": () => import("../components/mockups/omniva-variants/CardPage.tsx"),
  "./components/mockups/omniva-variants/DarkPremium.tsx": () => import("../components/mockups/omniva-variants/DarkPremium.tsx"),
  "./components/mockups/omniva-variants/EditorialGrid.tsx": () => import("../components/mockups/omniva-variants/EditorialGrid.tsx"),
  "./components/mockups/omniva-variants/ProductLaunch.tsx": () => import("../components/mockups/omniva-variants/ProductLaunch.tsx")
};
